# Generated by Django 4.1.7 on 2023-03-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('body', models.TextField()),
            ],
        ),
    ]
