# Generated by Django 4.1.7 on 2023-03-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
