# Generated by Django 4.1.7 on 2023-03-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
